stages:
  data_preprocessing:
    cmd: python src/covid_md/pipeline/stage_01_data_preprocessing.py
    deps:
      - src/covid_md/pipeline/stage_01_data_preprocessing.py
      - configs/config.yaml
    outs:
      - artifacts/data_preprocess/data.npy
      - artifacts/data_preprocess/target.npy
  data_training:
    cmd: python src/covid_md/pipeline/stage_02_data_training.py
    deps:
      - src/covid_md/pipeline/stage_02_data_training.py
      - configs/config.yaml
      - params.yaml
      - artifacts/data_preprocess/data.npy
      - artifacts/data_preprocess/target.npy
    outs:
      - artifacts/data_training
  mask_detection:
    cmd: python src/covid_md/pipeline/stage_03_mask_detection.py
    deps:
      - src/covid_md/pipeline/stage_03_mask_detection.py
      - artifacts/data_training
      - configs/config.yaml