artifacts_root: artifacts

data_preprocessing:
  root_dir: artifacts/data_preprocess
  data_path: collected_data
  preprocess_records: artifacts/data_preprocess

data_training:
  root_dir: artifacts/data_training
  data_path: artifacts/data_preprocess

mask_detection:
  root_dir: artifacts/data_training
  face_classifier: haarcascade_frontalface_default.xml
